# Generated by Django 4.2.11 on 2024-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("notifications", "0001_initial"),
=======
        ('notifications', '0001_initial'),
>>>>>>> 20d5f52ef1d7d03304aa3abc20f5e37cc8590b2c
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("DM", "Direct Message"), ("GROUP", "Group Message")],
                default="DM",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_id",
=======
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DM', 'Direct Message'), ('GROUP', 'Group Message')], default='DM', max_length=5),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
>>>>>>> 20d5f52ef1d7d03304aa3abc20f5e37cc8590b2c
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
