# Generated by Django 4.2.11 on 2024-07-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_user_course_alter_user_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
