# Generated by Django 4.2.11 on 2024-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_post_boost_expires_at_post_is_boosted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
